gameloanguru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.urls import path


from . import views

app_name = 'mainapp'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    path('game/<int:game_id>/', views.game, name='game'),
    path('mygames/', views.mygames, name='mygames'),
    path('allgames/', views.allgames, name='allgames'),
    path('addgame/', views.addgame, name='addgame'),
    path('editgame/<int:game_id>/', views.editgame, name='editgame'),
    path('reserve/<int:game_id>/', views.reserve, name='reserve'),
    path('new_loan/<int:game_id>/', views.new_loan, name='new_loan'),
]

users/urls.py
from django.urls import path,include

from . import views

app_name = 'users'
urlpatterns = [
    #users page / django defaults
    path('', include('django.contrib.auth.urls')),
    
    # USer registration.
    path('register/', views.register, name='register'),
]

mainapp/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

class Game(models.Model):
    """A Game a user can loan"""
    name = models.CharField(max_length=200)
    
    summary = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    

    LOAN_STATUS = (
        ('a', 'Available'),
        ('o', 'On loan'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
        help_text='Game availability',
    )

    def __str__(self):
        """This will return the title of the Book"""
        return f"{self.name[:50]}..."



"""A Loan event for a game"""
class Loan(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    LOAN_ACTION = (
        ('r', 'Reserve'),
        ('l', 'Loan Out'),
        ('r', 'Return'),
    )

    action = models.CharField(
        max_length=1,
        choices=LOAN_ACTION,
        blank=True,
        default='r',
        help_text='Loan action',
    )

    date_added = models.DateTimeField(auto_now_add = True)
    date_modified = models.DateTimeField(auto_now_add = True)

   
            
    def __str__(self):
        """Return a string of the loan"""
        return f"{self.action}"

users/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms
from .models import Game, Loan

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'summary', 'status']
        labels = {'name': 'Name:', 'summary': 'Summary:', 'status' : 'status'}

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['action']
        labels = {'action': 'Action:'}

mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.
from .models import Game, Loan
from .forms import GameForm, LoanForm

def index(request):
    allgames = Game.objects.order_by('date_added')
    context = {'allgames' : allgames}
    return render(request, 'mainapp/index.html', context)
    
def allgames(request):
    """Show all games."""
    games = Game.objects.order_by('date_added')  
    context = {'games': games}
    return render(request, 'mainapp/allgames.html', context)

@login_required
def mygames(request):
    mygames = Game.objects.filter(owner=request.user).order_by('date_added')
    context = {'mygames' : mygames}
    return render(request, 'mainapp/mygames.html', context)

@login_required
def game(request, game_id):
    """Show a single book and all it's reviews."""
    game = Game.objects.get(id=game_id)
    owner = game.owner
    summary = game.summary
    status = game.status
    #loans = Game.loan_set.order_by('-date_added')
    context = {'game': game, 'summary': summary, 'status': status} #'loans': loans}
    return render(request, 'mainapp/game.html', context)

@login_required
def addgame(request):


    """Add a new game."""
    if request.method != 'POST':
        #No data submitted; create a blank form
        form = GameForm()
    else:
        # POST data submitted; process data.
        form = GameForm(data=request.POST)
        if form.is_valid():
            newgame = form.save(commit=False)
            newgame.owner = request.user
            newgame.save()
            return redirect('mainapp:allgames')
    
    #Display a blank or invalid form.
    context = {'form':form}
    return render(request, 'mainapp/addgame.html', context)

login_required
def editgame(request, game_id):
    """Edit an existing game."""
    
    game = Game.objects.get(id=game_id)
    
    # Make sure the game belongs to the current user.
    if game.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current review.
        form = GameForm(instance=game)
    else:
        # POST data submitted; process data.
        form = GameForm(instance=game, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('mainapp:game', game_id=game.id)

    context = {'game' : game, 'form': form}
    return render(request, 'mainapp/editgame.html', context)

def new_loan(request, game_id):
    """Show a loan for a certain game."""
    game = Game.objects.get(id=game_id)
    #loan = Loan.objects.order_by('date_added') 

    if request.method != 'POST':
        #No data submitted; process data.
        form = LoanForm(instance=game)
    else:
        # POST data submitted; process data.
        form = LoanForm(data=request.POST)
        if form.is_valid():
            reserve = form.save(commit=False)
            reserve.owner = request.user
            reserve.game = game

            if loan.action == 'r':
                game.status = 'r'
            elif loan.action == 'l':
                game.status = 'o'
            else:
                game.status = 'a'
            reserve.save()
            return redirect('mainapp:game', game_id=game_id)
    
    #Display a blank or invalid form.
    context = {'game': game, 'form': form}
    return render(request, 'mainapp/reserve.html', context)

@login_required 
def reserve(request, game_id):
    """Add a new reservation to loan a particular boardgame."""
    game = Game.objects.get(id=game_id)
    
    if request.method != 'POST':
        #No data submitted; process data.
        form = LoanForm()
    else:
        # POST data submitted; process data.
        form = LoanForm(data=request.POST)
        if form.is_valid():
            reserve = form.save(commit=False)
            reserve.owner = request.user
            reserve.game = game
            game.status = 'r'
            
            reserve.save()
            return redirect('mainapp:game', game_id=game_id)
    
    #Display a blank or invalid form.
    context = {'game': game, 'form': form}
    return render(request, 'mainapp/reserve.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process complete form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('mainapp:index')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

mainapp/templates/mainapp/addgame.html
{% extends "mainapp/base.html"%}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">Add a Game</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
  {% endblock page_header %}
{% block content %}
  <div class="container">

  <form action="{% url 'mainapp:addgame'%}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      
      <button name="submit">Add a game</button>
  </form>
</div>
{% endblock content %}  

mainapp/templates/mainapp/allgames.html
{% extends "mainapp/base.html"%}

{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">All Games</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
{% endblock page_header %}
{% block content %}

 <div class="container">
  
    <div class="row">
       <div class="col-md-3 themed-grid-col">Name</div>
       <div class="col-md-3 themed-grid-col">Owner</div>
       <div class="col-md-3 themed-grid-col">Summary</div>
       <div class="col-md-3 themed-grid-col"></div>
     </div>
     <hr>
    <div class="row">
			
      {% for game in games %}
      <div class="col-md-3 themed-grid-col"><a href="{%url 'mainapp:game' game.id %}">{{ game.name }}</a></div>
      <div class="col-md-3 themed-grid-col">{{ game.owner}}</div>
      <div class="col-md-3 themed-grid-col">{{ game.summary }}</div>
      <div class="col-md-3 themed-grid-col"></div>
      
    
   {% empty %}
     <div class="col-md-4 themed-grid-col"> No games added yet</div>
   {% endfor %}
    </div>
   

  </div> 

{% endblock content %}

mainapp/templates/mainapp/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0", shrink-to-fit="no">
    <title>GameLoanGuru</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    
    <nav style="background-color: #396EB0!important;" class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'mainapp:index' %}">
            <img src="{% static 'GameLoanGuru.png' %}" 
            width="100" height="100" class="img-thumbnail" alt="GameloanguruLogo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div  class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
               
               
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <li class="nav-item">
                    <a class="nav-link" style="color: #FC997C !important"  href="{% url 'mainapp:allgames' %}">All Games</a>
                </li>
                    <a class="nav-link" style="color: #FC997C !important" href="{% url 'mainapp:mygames' %}">My Games</a>
                    
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" style="color: #FC997C !important" href="{% url 'users:logout' %}">Logout,{{ user.username }}</a>
                </li>
               
                    {% else %}
                    <li class="nav-item" >
                        <a class="nav-link" style="color: #FC997C !important" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item"></li>
                    <a class="nav-link" style="color: #FC997C !important" href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% endif %}
               
                
            </ul>
        </div>
    </nav>


    {% block page_header %}{% endblock page_header %}
    {% block content %}{% endblock content %}
</body>
</html>

mainapp/templates/mainapp/editgame.html
{% extends "mainapp/base.html" %}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">Edit Game</h1>
      <p style="color: #FC997C !important"></p>
    </div>
  </div>
  {% endblock page_header %}
  {% block content %}
  <div class="container">
  <form action = "{% url 'mainapp:editgame' game.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
   <input type="submit" value="Save">
  </form>
</div>
  {% endblock content %}

mainapp/templates/mainapp/game.html
{% extends 'mainapp/base.html' %}

{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">{{ game.name }}</h1>
      <p style="color: #FC997C !important"></p>
    </div>
  </div>
  {% endblock page_header %}

{% block content %}
       
<div class="container">
        
        
           
        
        <h2>Title:</h2>
        <div class="col-md-3 themed-grid-col">{{ game.name }}</div>
        <hr>
        <h2>Summary of the game:</h2>
        <div class="col-md-3 themed-grid-col">{{ game.summary }}</div>
        <hr>
        <h2>Owner:</h2>
        <div class="col-md-3 themed-grid-col">{{ game.owner }}</div>
        <hr>
        Status:
        {% if game.status == 'a' %}
          Available <a href="{% url 'mainapp:new_loan' game.id %}">Loan this game:</a>
        {% else %}
        Not available
        {% endif %}

        <p></p>
        Game added:
        <div class="col-md-3 themed-grid-col">{{ game.date_added }}</div>
        
        {% for loan in loans %}
          <div class="card mb-3">
                  <h4 class="card-header">
                        {{ loan.date_added|date:'M d, Y H:i' }}
                        <small><a href="{% url 'mainapp:editloan' loan.id %}">Edit loan</a></small>
                  </h4>
                  <div class="card-body">
                        {{ loan.date_added|linebreaks }}
                  </div>
          </div>
               
        {% empty %}
                <p>This game has not been loaned yet.</p>
        {% endfor %}
        
</div>      
{% endblock content%}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}

{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">GameLoanGuru</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
  {% endblock page_header %}
  {% block content %}
  {% if user.is_authenticated %}
 
  {% else %}
  <div class="container">
	<div class="row">
        <!-- Boxes -->
    	<div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-thumbs-o-up"></i></div>
					<div class="info">
						<h3 class="title">Register</h3>
						<p>
							To add your own games to your library and start loaning games from other users
						</p>
						<div class="more">
							<a class="btn btn-primary" href="{% url 'users:register' %}" role="button">Register</a>
							
						</div>
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>
			
        <div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-flag"></i></div>
					<div class="info">
						<h3 class="title">Get access to an extensive library</h3>
    					<p>
							Follow who has your games and when you need to return games you have loaned
						</p>
						
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>
			
        <div class="col-xs-12 col-sm-6 col-lg-4">
			<div class="box">							
				<div class="icon">
					<div class="image"><i class="fa fa-desktop"></i></div>
					<div class="info">
						<h3 class="title">Have fun</h3>
    					<p>
							Have fun with your friends and make new friends
						</p>
						
					</div>
				</div>
				<div class="space"></div>
			</div> 
		</div>		    
		<!-- /Boxes -->
	</div>
</div>
{% endif %}
<hr>
<div class="container">
	<h3>Check out what available games users have for loaning right now.</h3>
	
	   <div class="row">
		<div class="col-md-3 themed-grid-col">Name</div>
		<div class="col-md-3 themed-grid-col">Owner</div>
		<div class="col-md-3 themed-grid-col">Summary</div>
		<div class="col-md-3 themed-grid-col"></div>
		
	  </div>
	  <hr>
		<div class="row">
			
		   	{% for game in allgames %}
			   <div class="col-md-3 themed-grid-col">{{ game.name }}</div>
				<div class="col-md-3 themed-grid-col">{{ game.owner}}</div>
				<div class="col-md-3 themed-grid-col">{{ game.summary}}</div>	
				<div class="col-md-3 themed-grid-col"></div>				
			{% empty %}
				<div class="col-md-1 themed-grid-col">
				No games available at the moment		
				</div>
				
			{% endfor %}
		</div>
</div>

{% endblock content %}

mainapp/templates/mainapp/mygames.html
{% extends "mainapp/base.html" %}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">My Games</h1>
      <p style="color: #FC997C !important"></p>
    </div>
</div>
{% endblock page_header %}
{% block content %}
  <div class="container">
       <div class="row">
          <div class="col-md-3 themed-grid-col">Name</div>
          <div class="col-md-3 themed-grid-col">Summary</div>
          <div class="col-md-3 themed-grid-col"></div>
          <div class="col-md-3 themed-grid-col"></div>
        </div>
       <ul>
        <div class="row">
			
          {% for game in mygames %}
          <div class="col-md-3 themed-grid-col"><a href="{%url 'mainapp:editgame' game.id %}">{{ game.name }}</a></div>
          <div class="col-md-3 themed-grid-col">{{ game.summary}}</div>
          <div class="col-md-3 themed-grid-col"></div>
          <div class="col-md-3 themed-grid-col"></div>
          
        
       {% empty %}
         <div class="col-md-4 themed-grid-col"> No games added yet</div>
       {% endfor %}
        </div>
       </ul>
       <hr>
       <div class="row mb-3"></div>
          <div class="col-md-4 themed-grid-col">
          <a class="btn btn-primary" href="{% url 'mainapp:addgame' %}" role="button">Add Game</a>
          </div>
        </div>
      </div>
    </div>
 
{% endblock content %}

mainapp/templates/mainapp/new_loan.html
{% extends 'mainapp/base.html' %}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">Make a new Loan</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
  {% endblock page_header %}
{% block content %}

  <p><a href="{% url 'mainapp:game' game.id %}">{{ game }}</a></p>

  <p>Make a new loan:</p>
  <form action="{% url 'mainapp:new_loan' game.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
      
      <button name="submit">Confirm</button>
  </form>

{% endblock content %}  

mainapp/templates/mainapp/newgame.html
{% extends "mainapp/base.html"%}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">Add a new Game</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
  {% endblock page_header %}
{% block content %}
  <p>Add a new game:</p>

  <form action="{% url 'mainapp:new_book'%}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      
      <button name="submit">Add a game</button>
  </form>

{% endblock content %}  

mainapp/templates/mainapp/reserve.html
{% extends 'mainapp/base.html' %}
{% block page_header %}
<div style="background-color: #2E4C6D!important;" class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 style="color: #FC997C !important" class="display-4">Make a reserve for a loan</h1>
      <p style="color: #FC997C !important">A network for loaning games to and from users</p>
    </div>
  </div>
  {% endblock page_header %}
{% block content %}
<div class="container">
  <p><a href="{% url 'mainapp:game' game.id %}"><h2>{{ game.name }}</h2></a></p>

  
  <form action="{% url 'mainapp:reserve' game.id %}" method='post'>
    {% csrf_token %}
    
    {{ form.as_p }}
    
      <button name="submit">Confirm</button>
  </form>
</div>
{% endblock content %}  